version: '3.8'

services:
  zonos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zonos_container
    ports:
      - "7860:7860"  # Map container port to host port
    stdin_open: true
    tty: true
    command: ["python3", "gradio_interface.py"]
    environment:
      - GRADIO_SHARE=False
    volumes:
     - ./model-cache:/root/.cache/huggingface/hub  # Mount local directory for model cache